<a href="https://colab.research.google.com/github/saks0106/Frequent-Lookouts/blob/main/Categorical_Encoding_Ordinal_Ohe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ordinal

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

review education purchased
13  Average    School        No
14     Poor        PG       Yes
26     Poor        PG        No
37  Average        PG       Yes
23     Good    School        No

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
X = df.drop('purchased',axis=1)
y = df['purchased']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=43)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
# OrdinalEncoder on Ordinal Categorical data: Eg PhD > Grad > HS > PS --> 4,3,2,1
# OHE on Nominal Categorical data

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]) #poor will get lowest value, good will get highest value

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train = oe.transform(X_train)

In [ ]:
X_train

array([[1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [1., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [1., 1.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder #only for target labels that are categorical

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0])

#Nominal

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['owner'].value_counts()

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

In [18]:
df['brand'].nunique()

32

## 1. OneHotEncoding using Pandas

In [5]:
pd.get_dummies(df,columns=['fuel','owner']) #brand later

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

## 2. K-1 OneHotEncoding

In [6]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True) 
# drop_first avoids multicollinearlity as 1st column is dropped and avoids dummy  variable trap
#but here drop_first will drop any random column,eg-fuel_CNG now, fuel_Diesel in later run. 
  #So we use sklearn as it remembers which column was in drop_first

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

## 3. OneHotEncoding using Sklearn

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [8]:
from sklearn.preprocessing import OneHotEncoder 

In [9]:
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32) # both columns 1st values will be dropped

In [10]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]) #ohe only on 2 columns

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [19]:
X_train_new ##by default sklearn ohe will produce sparse matrix

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [11]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [12]:
X_train_new.shape

(6502, 7)

In [ ]:
#combining to np arrays using hstack

In [13]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

## 4. OneHotEncoding with Top Categories

In [20]:
counts = df['brand'].value_counts()
counts

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [22]:
df['brand'].nunique()

32

In [23]:
threshold = 100

In [21]:
repl = counts[counts <= threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object')

In [27]:
brands_common = df['brand'].replace(repl, 'uncommon') #count of values < 100, replace with 'uncommon'

In [28]:
pd.get_dummies(brands_common).sample(5)

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
2066    0          0     0      0        0         0       0        0      0   
2525    0          0     0      0        0         0       1        0      0   
530     0          0     0      0        1         0       0        0      0   
2022    0          0     1      0        0         0       0        0      0   
7416    0          0     0      0        0         0       1        0      0   

      Tata  Toyota  Volkswagen  uncommon  
2066     1       0           0         0  
2525     0       0           0         0  
530      0       0           0         0  
2022     0       0           0         0  
7416     0       0           0         0