<a href="https://colab.research.google.com/github/saks0106/Frequent-Lookouts/blob/main/minibatch_gd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y = load_diabetes(return_X_y=True)

In [8]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [6]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [7]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [11]:
X_train[[0,1,2]]

array([[-0.00188202, -0.04464164, -0.06979687, -0.01255612, -0.00019301,
        -0.00914259,  0.07072993, -0.03949338, -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, -0.05731319, -0.02496016,
        -0.04296262,  0.03023191, -0.03949338,  0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, -0.03665608, -0.01395254,
        -0.01509241,  0.05968501, -0.03949338, -0.09643495, -0.01764613]])

In [12]:
X_train[0]

array([-0.00188202, -0.04464164, -0.06979687, -0.01255612, -0.00019301,
       -0.00914259,  0.07072993, -0.03949338, -0.06291688,  0.04034337])

In [14]:
import random
random.sample(range(X_train.shape[0]),10)

[225, 78, 352, 219, 110, 43, 284, 157, 297, 46]

In [15]:
X_train.shape[0]

353

In [16]:
X_train[random.sample(range(X_train.shape[0]),10)]

array([[-0.07453279,  0.05068012, -0.00943939,  0.01498668, -0.03734373,
        -0.02166853, -0.01394774, -0.00259226, -0.03324559,  0.01134862],
       [-0.02367725, -0.04464164, -0.046085  , -0.03321323,  0.03282986,
         0.03626394,  0.03759519, -0.00259226, -0.03324559,  0.01134862],
       [-0.04547248,  0.05068012, -0.04716281, -0.01599898, -0.04009564,
        -0.02480001,  0.00077881, -0.03949338, -0.06291688, -0.03835666],
       [ 0.02717829,  0.05068012,  0.09403057,  0.09761511, -0.03459183,
        -0.03200243, -0.04340085, -0.00259226,  0.03664373,  0.10661708],
       [-0.02367725, -0.04464164,  0.04013997, -0.01255612, -0.00982468,
        -0.00100073, -0.00290283, -0.00259226, -0.01189685, -0.03835666],
       [ 0.02354575,  0.05068012, -0.03207344, -0.04009893, -0.03183992,
        -0.02166853, -0.01394774, -0.00259226, -0.01090325,  0.01963284],
       [-0.02730979, -0.04464164, -0.06009656, -0.02977038,  0.04658939,
         0.01998022,  0.12227286, -0.03949338

In [17]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size) 
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [18]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [19]:
mbr.fit(X_train,y_train)

149.01323877510703 [  27.86634651 -152.27111155  445.86024556  303.60230782  -26.17498403
  -91.15957209 -197.0298968   115.80484832  404.9548669   115.83036837]


In [20]:
y_pred = mbr.predict(X_test)

In [21]:
r2_score(y_test,y_pred)

0.4537575200773363

In [22]:
#we don't have mini batch option in SGDRegressor, so we make some tweaks which are below
from sklearn.linear_model import SGDRegressor

In [23]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [24]:
batch_size = 35

for i in range(100): #100 epochs
    
    idx = random.sample(range(X_train.shape[0]),batch_size) #35 random values
    sgd.partial_fit(X_train[idx],y_train[idx]) # only random 35 values sent to training

In [25]:
sgd.coef_

array([  55.33142224,  -70.29512252,  359.28541236,  250.07623338,
         22.28742744,  -16.23736837, -174.02541135,  126.46669249,
        306.62534664,  142.04957834])

In [26]:
sgd.intercept_

array([155.43479301])

In [27]:
y_pred = sgd.predict(X_test)

In [28]:
r2_score(y_test,y_pred)

0.43240543039747936