<a href="https://colab.research.google.com/github/saks0106/ML_Frequent-Lookouts/blob/main/Quick_Reference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Examples

In [ ]:
pd.Series([1,2,3],index=['a','b','c'])

In [ ]:
pd.Series(range(1,10),index=[i for i in range (1,10)])

In [ ]:
#wherever cyl is 6, give drat mean
cars.loc[(cars['cyl']==6),'drat'].mean() - cars.loc[(cars['cyl']==8),'drat'].mean()


#df[(df['Doors'] >= 4)]['Doors'].count()
#df[(df['Doors']>=4)]['Colour'].unique().tolist()

0.35642857142857176

In [ ]:
cars['cyl'].value_counts().keys().unique()
#cars['model'].value_counts().sort_values(ascending=False)
#cars.model.value_counts().reset_index().sort_values('model', ascending=False)


Int64Index([8, 4, 6], dtype='int64')

In [ ]:
pd.DataFrame({'Skewness':[stats.skew(df.bmi), stats.skew(df.age),stats.skew(df.expenses)]},index=['Bmi','Age','Expenses'])

In [ ]:
# Dataframe of number of sales made by an employees
sales = {'Jones': 10000,
         'Chris': 5000,
         'Piyush': 440,
         'Meera': 6700,
         'Rahul': 300
        }
# Dataframe of all employees and the region they work in
region = {'Jones': 'West',
          'Chris': np.nan,
          'Piyush': 'West',
          'Meera': np.nan,
          'Anthony': 'East',
          'Ellen': 'South',
          'Josh': 'West',
          'Simran': 'East',
          'Oscar': 'North',
         }

sales = pd.DataFrame.from_dict(sales,orient='index',columns=['sales'])
region = pd.DataFrame.from_dict(region,orient='index',columns=['region'])
joined = sales.join(region,how='outer')

#for merging
region.index.name = 'names'
sales.index.name = 'names'

merged = pd.merge(region,sales,how='outer',on='names')

In [ ]:
age_map = {'18+':18,'7+':7,'13+':13,'all':0,'16+':16}
df['Age_Copy'] = df['Age'].map(age_map)

In [ ]:
churn_data['TotalCharges']=pd.to_numeric(churn_data['TotalCharges'], errors='coerce')# error =corece to handle the error
churn_data['gender'] = churn_data['gender'].map({'Male': 1, 'Female': 0})

In [ ]:

my_dict = {1: 'A',
           2: 'B',
           3: 'C'
        }
 

result = my_dict.items()
 

data = list(result)
 
numpyArray = np.array(data)
 
print(numpyArray)

In [ ]:
df['cyl'].between(20,26).sum()



In [ ]:
cars.loc[(cars['cyl']==8) & (cars['carb']==4)]#.value_counts() #| for or

S.No                model   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
6      7           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   
14    15   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   
15    16  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   
16    17    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   
23    24           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   
28    29       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   

    am  gear  carb  
6    0     3     4  
14   0     3     4  
15   0     3     4  
16   0     3     4  
23   0     3     4  
28   1     5     4

In [ ]:
cars.cyl.replace((8, 4), (8.1, 4.2), inplace=True)

In [ ]:
cars['cyl'].unique(), len(cars['cyl'].unique().tolist())

(array([6. , 4.2, 8.1]), 3)

In [ ]:
np.where(titanic.age<=1, "NewBorn", "Not NewBorns")

In [ ]:
s = pd.Series(['a','b','c',12,13,13,'d','e'])
s.index, s.dtype, s.ndim, s.values,s.mean,s

In [ ]:
# Using Heatmap to check null values
sns.set_style('whitegrid') # use it for countplot
sns.heatmap(cars.isna(),yticklabels=False)
#Because we have no nulls, it shows nothing

In [ ]:
#Handling Missing Values
mf = lambda x: x.fillna(x.median())
df3 = df2.apply(mf,axis=0)


#df3['horsepower'] = df3['horsepower'].fillna(df3['horsepower'].median())

#df['Odometer'].fillna(df['Odometer'].mean(),inplace=True) # 
#df['Odometer'].fillna(method='ffill')

In [ ]:
cars.groupby(['model'])['wt']

In [ ]:
cars.groupby(['model'])['wt'].aggregate('sum').reset_index().sort_values('model', ascending=False)
#aggregate can be changed to max, min, sum

#df.groupby(['SeniorCitizen'])['tenure'].aggregate('count')
#df.groupby(['SeniorCitizen'])['tenure'].mean()

#df.groupby(['Odometer'])['Odometer'].aggregate(['mean','median'])

#df['Odometer'].aggregate(['mean','median'])


# t.groupby(['pclass','sex'])['fare'].agg('count')#aggregate('count')
# t.groupby(['pclass','sex'])['fare'].agg(['mean','median'])#aggregate('count')
# t.groupby(['pclass','sex'])['fare'].mean()

In [ ]:
#visualize using crosstab
pd.crosstab(y_test,y_preds,rownames=['Actual'],colnames=['Predicted'])

In [ ]:
pd.get_dummies(cars,columns=['model'],drop_first=True) # will drop the very first dummies column to avoid dummy varaible trap

In [ ]:
cars['model'].value_counts().keys().to_list()

In [ ]:
df['Company']= df['Company'].str.lower()

In [ ]:
hd.sort_values(by='cp',ascending=False)


result_data = df[(df['age'] >60) & (df['target'] ==1)]

df = pd.DataFrame(result_data, index = None)
  
# computing number of rows
rows = len(df.axes[0])
  
# computing number of columns
cols = len(df.axes[1])

In [ ]:
#Let's check for multicollinearity - OLS ie Ordinary Least Square method, intercept ie C is initally multiplied by 1
import statsmodels.api as sm

X = sm.add_constant(X)
model = sm.OLS(y,X).fit() #output feature, input features

model.summary()
#R-squared is 0.825 which is good, coef is something that should be adjusted to get best reults
#std err is also very less indicating none of the feaure have multicollinearity, if high multicollinearity can exist
      #if std err is huge, remove that feature that has high pvalue
# p value should be less than 5% and except for horsepower and accleration, all are below 5%

In [ ]:
a = np.array([['Sak',"Pra"],
              ["60000","70000"],
              ['Data Scientist','Developer']])
pd.DataFrame({"Employee":a[0],"Salary":a[1],'Designation':a[2]})

Employee Salary     Designation
0      Sak  60000  Data Scientist
1      Pra  70000       Developer

In [ ]:
df = pd.DataFrame({'Animal':['Tiger','Lion','Dog'],
                 'Color':['Golden','Yellow','Blue'],
                 'Price':[12,34,3]},
                  index=['A','B','C'])
df.columns,df.index,df.values,df.dtypes,len(df),type(df)

In [ ]:
df.reset_index()
df.set_index('Title') # key='Title'
#df.set_index(keys='Company')

In [ ]:
# to rename the column
df.rename(columns={"Make":"Company"},inplace=True)

In [ ]:
#to change a particular value 
df.at[9,'Company']='Lamborghini'
#df.iloc[8,1] = 'Violet'

In [ ]:
pd.crosstab(df['Price'],df['Company'])

Company      BMW  Honda  Nissan  Toyota
Price                                  
$22,000.00     1      0       0       0
$3,500.00      0      0       1       0
$4,000.00      0      0       0       1
$4,500.00      0      0       0       1
$5,000.00      0      1       0       0
$6,250.00      0      0       0       1
$7,000.00      0      1       0       1
$7,500.00      0      1       0       0
$9,700.00      0      0       1       0

In [ ]:
df.loc[:4,['Doors','Price']]
df.iloc[:4,[3,4]]
df.iloc[[3,4],[3,4]]
df.iloc[4:,2:]
df.loc[(t['pclass']==1) & (t['sex']=='male'),'fare'].mean()

In [ ]:
df.dropna(subset=['Make','Doors','Price'],inplace=True,axis=0,how='all')
# how = any --> if any value in a row is null drop it, all--> if all values in a row are null, drop it

In [ ]:
df[df['Make'].astype(str).str.contains('H')] # in make which is string, give results that contain H

Make Colour  Odometer  Doors   Price
1  Honda    Red   87899.0    4.0  $5,000
6  Honda    NaN       NaN    4.0  $7,500
7  Honda   Blue       NaN    4.0     NaN

In [ ]:
df[df['Make'].isin(df['Make'].tolist())][['Make', 'Colour', 'Odometer', 'Doors']]

Make Colour  Odometer  Doors
0  Toyota  White  150043.0    4.0
1   Honda    Red   87899.0    4.0
2  Toyota   Blue       NaN    3.0
3     BMW  Black   11179.0    5.0
4  Nissan  White  213095.0    4.0
5  Toyota  Green       NaN    4.0
6   Honda    NaN       NaN    4.0
7   Honda   Blue       NaN    4.0
8  Toyota  White   60000.0    NaN
9     NaN  White   31600.0    4.0

In [ ]:
t['age'].fillna(t['age'].mode,axis=0,inplace=True)

#dropping rows of dataframe
td.drop(labels=[4,6],axis=0)


In [ ]:
player = ['sak','pra','sum']
point = [8,9,10]
title = ['G1','G2','G3']
df1 = pd.DataFrame({"Players":player,"Points":point,"Titles":title})
df1

Players  Points Titles
0     sak       8     G1
1     pra       9     G2
2     sum      10     G3

In [ ]:
player = ['sak','ros','che']
power = [81,91,110]
title = ['G4','G5','G1']
df2 = pd.DataFrame({"Players":player,"Power":power,"Titles":title})
df2

Players  Power Titles
0     sak     81     G4
1     ros     91     G5
2     che    110     G1

In [ ]:
df1.merge(df2,on='Titles',how='right')
# inner(default),left(df1 all values will be there),outer(all), right(df2 all values will be there)

Players_x  Points Titles Players_y  Power
0       NaN     NaN     G4       sak     81
1       NaN     NaN     G5       ros     91
2       sak     8.0     G1       che    110

In [ ]:
pd.concat([df1,df2])

Players  Points Titles  Power
0     sak     8.0     G1    NaN
1     pra     9.0     G2    NaN
2     sum    10.0     G3    NaN
0     sak     NaN     G4   81.0
1     ros     NaN     G5   91.0
2     che     NaN     G1  110.0

# Numpy Examples

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([[1,2,3.]])
type(a1), len(a1), a1.shape,a1.ndim,a1.dtype, a1.size

(numpy.ndarray, 1, (1, 3), 2, dtype('float64'), 3)

In [ ]:
a2 = np.array([[1,2,3],
               [4,5,6]],dtype=float)
type(a2),len(a2),a2.shape,a2.ndim,a2.dtype,a2.size

(numpy.ndarray, 2, (2, 3), 2, dtype('float64'), 6)

In [ ]:
a3 = np.sum([a1,a2],dtype=object)
type(a3),len(a3),a3.shape,a3.ndim,a3.dtype

C:\Users\acer\Desktop\sample_project_1\env\lib\site-packages\numpy\core\fromnumeric.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


(numpy.ndarray, 2, (2, 3), 2, dtype('float64'))

In [ ]:
a4 = np.array([[[1,2,3.3],
              [4.5,5.6,6.5],
              [7.5,8,9]],
             [[1,2,3],
              [4,5,6],
              [7,8,9]]])
type(a4),len(a4), a4.shape,a4.ndim,a4.dtype,a4.size

(numpy.ndarray, 2, (2, 3, 3), 3, dtype('float64'), 18)

In [ ]:
a4

array([[[1. , 2. , 3.3],
        [4.5, 5.6, 6.5],
        [7.5, 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

In [ ]:
a4.reshape(9,2)

array([[1. , 2. ],
       [3.3, 4.5],
       [5.6, 6.5],
       [7.5, 8. ],
       [9. , 1. ],
       [2. , 3. ],
       [4. , 5. ],
       [6. , 7. ],
       [8. , 9. ]])

In [ ]:
a4.reshape(-1,9,2)

array([[[1. , 2. ],
        [3.3, 4.5],
        [5.6, 6.5],
        [7.5, 8. ],
        [9. , 1. ],
        [2. , 3. ],
        [4. , 5. ],
        [6. , 7. ],
        [8. , 9. ]]])

In [ ]:
a4.reshape(9,2,-1)

In [ ]:
a4.reshape(-1,2,3,3)

array([[[[1. , 2. , 3.3],
         [4.5, 5.6, 6.5],
         [7.5, 8. , 9. ]],

        [[1. , 2. , 3. ],
         [4. , 5. , 6. ],
         [7. , 8. , 9. ]]]])

In [ ]:
a4.reshape(2,3,3)

array([[[1. , 2. , 3.3],
        [4.5, 5.6, 6.5],
        [7.5, 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

In [ ]:
a4.reshape(-1,1)

array([[1. ],
       [2. ],
       [3.3],
       [4.5],
       [5.6],
       [6.5],
       [7.5],
       [8. ],
       [9. ],
       [1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [6. ],
       [7. ],
       [8. ],
       [9. ]])

In [ ]:
a4[:2,:3,:1]

array([[[1. ],
        [4.5],
        [7.5]],

       [[1. ],
        [4. ],
        [7. ]]])

In [ ]:
a4[:2,:3,1]

array([[2. , 5.6, 8. ],
       [2. , 5. , 8. ]])

In [ ]:
a4

array([[[1. , 2. , 3.3],
        [4.5, 5.6, 6.5],
        [7.5, 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

In [ ]:
a4[:1,:1,:1],a4[:1,:1,2]

(array([[[1.]]]), array([[3.3]]))

In [ ]:
a4[:1,:1,1]=3.2332
a4

array([[[1.    , 3.2332, 3.3   ],
        [4.5   , 5.6   , 6.5   ],
        [7.5   , 8.    , 9.    ]],

       [[1.    , 2.    , 3.    ],
        [4.    , 5.    , 6.    ],
        [7.    , 8.    , 9.    ]]])

In [ ]:
pow(a1,3)

array([[ 1.,  8., 27.]])

In [ ]:
a1

array([[1., 2., 3.]])

In [ ]:
a1+1, a1<5, a1.cumprod(),a2.flatten()

(array([[2., 3., 4.]]),
 array([[ True,  True,  True]]),
 array([1., 2., 6.]),
 array([1., 2., 3., 4., 5., 6.]))

In [ ]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
a2.reshape(-1,3,2)

array([[[1., 2.],
        [3., 4.],
        [5., 6.]]])

In [ ]:
np.swapaxes(a2,0,1)# a2 is of 2 dims, 0--row, 1-column

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [ ]:
a4

array([[[1. , 2. , 3.3],
        [4.5, 5.6, 6.5],
        [7.5, 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

In [ ]:
np.swapaxes(a4,2,1)

array([[[1. , 4.5, 7.5],
        [2. , 5.6, 8. ],
        [3.3, 6.5, 9. ]],

       [[1. , 4. , 7. ],
        [2. , 5. , 8. ],
        [3. , 6. , 9. ]]])

In [ ]:
np.swapaxes(a4,1,2) ==np.swapaxes(a4,2,1)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [ ]:
a3

array([[2., 4., 6.],
       [5., 7., 9.]])

In [ ]:
a3.sum(axis=0),a3.sum(axis=1),a3.cumsum(axis=0),a3.cumsum(axis=1)

(array([ 7., 11., 15.]),
 array([12., 21.]),
 array([[ 2.,  4.,  6.],
        [ 7., 11., 15.]]),
 array([[ 2.,  6., 12.],
        [ 5., 12., 21.]]))

In [ ]:
np.log(a3),np.log10(a3)

(array([[0.69314718, 1.38629436, 1.79175947],
        [1.60943791, 1.94591015, 2.19722458]]),
 array([[0.30103   , 0.60205999, 0.77815125],
        [0.69897   , 0.84509804, 0.95424251]]))

In [ ]:
np.linalg.inv(a4), np.linalg.det(a4)

(array([[[ 3.26530612e-01, -1.71428571e+00,  1.11836735e+00],
         [-1.68367347e+00,  3.21428571e+00, -1.70408163e+00],
         [ 1.22448980e+00, -1.42857143e+00,  6.93877551e-01]],
 
        [[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
         [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
         [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]]]),
 array([-4.90000000e+00, -9.51619735e-16]))

In [ ]:
# for checking dimension
np.linalg.matrix_rank(a4),a4.ndim, a4.mean()

(array([3, 2], dtype=int64), 3, 5.133333333333334)

In [ ]:
pd.DataFrame(a3)

0    1    2
0  2.0  4.0  6.0
1  5.0  7.0  9.0

In [ ]:
#Numpy arrays
np.linspace(-4,4,61)

array([-4.        , -3.86666667, -3.73333333, -3.6       , -3.46666667,
       -3.33333333, -3.2       , -3.06666667, -2.93333333, -2.8       ,
       -2.66666667, -2.53333333, -2.4       , -2.26666667, -2.13333333,
       -2.        , -1.86666667, -1.73333333, -1.6       , -1.46666667,
       -1.33333333, -1.2       , -1.06666667, -0.93333333, -0.8       ,
       -0.66666667, -0.53333333, -0.4       , -0.26666667, -0.13333333,
        0.        ,  0.13333333,  0.26666667,  0.4       ,  0.53333333,
        0.66666667,  0.8       ,  0.93333333,  1.06666667,  1.2       ,
        1.33333333,  1.46666667,  1.6       ,  1.73333333,  1.86666667,
        2.        ,  2.13333333,  2.26666667,  2.4       ,  2.53333333,
        2.66666667,  2.8       ,  2.93333333,  3.06666667,  3.2       ,
        3.33333333,  3.46666667,  3.6       ,  3.73333333,  3.86666667,
        4.        ])

In [ ]:
aa = np.arange(2,34,2).reshape(4,4)
aa

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [ ]:
my_list = [10,20,30,'apple',True,8.10]
my_list.extend([30,40])
my_list.reverse()
reversedList = my_list.copy()
reversedList   

[40, 30, 8.1, True, 'apple', 30, 20, 10]

In [ ]:
my_tuple = (1,2,3,'apple','mango')
my_tuple
numeric_tuple = (10,20,30,40,50)
min(numeric_tuple)
my_tuple += numeric_tuple
r1 = my_tuple
newdupli = []
for i in r1:
    newdupli.append(i)
for i in r1:
    newdupli.append(i)
list(newdupli)
newdupli

[1,
 2,
 3,
 'apple',
 'mango',
 10,
 20,
 30,
 40,
 50,
 1,
 2,
 3,
 'apple',
 'mango',
 10,
 20,
 30,
 40,
 50]

In [ ]:
set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}
union= set1.union(set2)
intersection = set1.intersection(set2)
difference = set1.difference(set2)
print(union,intersection,difference)

{1, 2, 3, 4, 5, 6, 7} {1, 2, 3} {4, 5}


In [ ]:
#hsplit is vertical split
np.hsplit(aa,2)

[array([[ 2,  4],
        [10, 12],
        [18, 20],
        [26, 28]]),
 array([[ 6,  8],
        [14, 16],
        [22, 24],
        [30, 32]])]

In [ ]:
aa

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [ ]:
#vsplit is horizontal split
np.vsplit(aa,2)

[array([[ 2,  4,  6,  8],
        [10, 12, 14, 16]]),
 array([[18, 20, 22, 24],
        [26, 28, 30, 32]])]

In [ ]:
np.random.random(size=(3,5)) # 0-1

array([[0.03772742, 0.81360256, 0.02360913, 0.36380361, 0.30999626],
       [0.71021288, 0.34755331, 0.50883741, 0.80329099, 0.50499152],
       [0.79936153, 0.97197601, 0.39362109, 0.8622963 , 0.28871154]])

In [ ]:
np.random.randint(1,30,size=15),np.random.randint(1,30,size=(3,5))

(array([ 1, 12, 21,  1, 12,  6, 14, 10, 19,  2, 11,  6, 10, 18, 16]),
 array([[18,  5,  7, 21, 16],
        [23, 24,  7,  7,  1],
        [ 9,  6, 28, 28, 28]]))

In [ ]:
np.random.normal(3, 1, size=(2, 4)) # 3 is normal distribution and 1 is SD

array([[3.4833718 , 3.77276325, 3.48890583, 3.25573833],
       [2.62996227, 4.52483633, 2.86772758, 2.64582163]])

In [ ]:
a = np.full((2,2),10)
a

array([[10, 10],
       [10, 10]])

In [ ]:
np.ones((2,2),dtype=int), np.eye(3)

(array([[1, 1],
        [1, 1]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [ ]:
b = np.random.randint(1,10,size=(2,2))
b

array([[2, 7],
       [7, 5]])

In [ ]:
np.unique(b)

array([2, 5, 7])

In [ ]:
np.concatenate((a,b))# np.hstack((a,b)) , np.column_stack((a,b))

array([[10, 10],
       [10, 10],
       [ 8,  3],
       [ 6,  9]])

In [ ]:
np.hstack((a,b)),np.vstack((a,b)),np.column_stack((a,b))

(array([[10, 10,  8,  3],
        [10, 10,  6,  9]]),
 array([[10, 10],
        [10, 10],
        [ 8,  3],
        [ 6,  9]]),
 array([[10, 10,  8,  3],
        [10, 10,  6,  9]]))

In [ ]:
a,b

(array([[10, 10],
        [10, 10]]),
 array([[8, 3],
        [6, 9]]))

In [ ]:
np.sum((a,b),axis=1),np.sum((a,b),axis=0),np.equal(a,b)

(array([[20, 20],
        [14, 12]]),
 array([[18, 13],
        [16, 19]]),
 array([[False, False],
        [False, False]]))

In [ ]:
np.add(a,b), np.subtract(a,b),np.multiply(a,b),np.divide(a,b), a*b , np.dot(a,b).reshape(-1,2,2)

(array([[12, 17],
        [17, 15]]),
 array([[8, 3],
        [3, 5]]),
 array([[20, 70],
        [70, 50]]),
 array([[5.        , 1.42857143],
        [1.42857143, 2.        ]]),
 array([[20, 70],
        [70, 50]]),
 array([[[ 90, 120],
         [ 90, 120]]]))

In [ ]:
np.square(a), np.power(a,3)

(array([[100, 100],
        [100, 100]], dtype=int32),
 array([[1000, 1000],
        [1000, 1000]], dtype=int32))

In [ ]:
np.exp(a), np.exp2(a)

(array([[22026.46579481, 22026.46579481],
        [22026.46579481, 22026.46579481]]),
 array([[1024., 1024.],
        [1024., 1024.]]))

In [ ]:
c = np.random.random(10000)

In [ ]:
#working with dot product
a = np.random.randint(10,size=(4,3))
b = np.random.randint(10,size=(4,3))

In [ ]:
a,b

(array([[3, 0, 3],
        [6, 1, 0],
        [0, 5, 5],
        [0, 2, 6]]),
 array([[0, 3, 4],
        [7, 5, 0],
        [3, 4, 2],
        [4, 2, 8]]))

In [ ]:
a*b

array([[ 0,  0, 12],
       [42,  5,  0],
       [ 0, 20, 10],
       [ 0,  4, 48]])

In [ ]:
b = b.T
b

array([[0, 7, 3, 4],
       [3, 5, 4, 2],
       [4, 0, 2, 8]])

In [ ]:
np.dot(a,b), np.matmul(a,b)

(array([[12, 21, 15, 36],
        [ 3, 47, 22, 26],
        [35, 25, 30, 50],
        [30, 10, 20, 52]]),
 array([[12, 21, 15, 36],
        [ 3, 47, 22, 26],
        [35, 25, 30, 50],
        [30, 10, 20, 52]]))

In [ ]:
a.shape, b.shape

((4, 3), (3, 4))

In [ ]:
np.random.seed(42)
sm = np.random.randint(20,size=(5,3))
sm

array([[ 6, 19, 14],
       [10,  7,  6],
       [18, 10, 10],
       [ 3,  7,  2],
       [ 1, 11,  5]])

In [ ]:
index = ['Monday','Tuesday','Wednesday','Thursday','Friday']
column = ['Almond','Peanut','Cashew']
df1 = pd.DataFrame(sm,index=index,columns=column)
df1

Almond  Peanut  Cashew
Monday          6      19      14
Tuesday        10       7       6
Wednesday      18      10      10
Thursday        3       7       2
Friday          1      11       5

In [ ]:
prices = np.array([10,8,12])#usin np.array and not series has reshape will not happen 
prices.shape

(3,)

In [ ]:
df2 = pd.DataFrame(prices.reshape(1,3),index=['PRICES'],columns=column)
df2

Almond  Peanut  Cashew
PRICES      10       8      12

In [ ]:
df3 = [df1,df2]
df3 = pd.concat(df3)
df3

Almond  Peanut  Cashew
Monday          6      19      14
Tuesday        10       7       6
Wednesday      18      10      10
Thursday        3       7       2
Friday          1      11       5
PRICES         10       8      12

In [ ]:
prices = prices.reshape(3,1)
prices, prices.shape

(array([[10],
        [ 8],
        [12]]),
 (3, 1))

In [ ]:
df4 = df1.dot(prices)
df4

0
Monday     380
Tuesday    228
Wednesday  380
Thursday   110
Friday     158

In [ ]:
df3['Total (₹)'] = df4
df3

Almond  Peanut  Cashew  Total (₹)
Monday          6      19      14      380.0
Tuesday        10       7       6      228.0
Wednesday      18      10      10      380.0
Thursday        3       7       2      110.0
Friday          1      11       5      158.0
PRICES         10       8      12        NaN

In [ ]:
a = pd.Series(df3['Total (₹)'])
df3.iloc[-1,-1] = a.sum()

In [ ]:
df3

Almond  Peanut  Cashew  Total (₹)
Monday          6      19      14      380.0
Tuesday        10       7       6      228.0
Wednesday      18      10      10      380.0
Thursday        3       7       2      110.0
Friday          1      11       5      158.0
PRICES         10       8      12     1256.0

In [ ]:
r = np.random.randint(10,size=(3,5))
r

array([[1, 4, 0, 9, 5],
       [8, 0, 9, 2, 6],
       [3, 8, 2, 4, 2]])

In [ ]:
np.sort(r),np.argsort(r)

(array([[0, 1, 4, 5, 9],
        [0, 2, 6, 8, 9],
        [2, 2, 3, 4, 8]]),
 array([[2, 0, 1, 4, 3],
        [1, 3, 4, 0, 2],
        [2, 4, 0, 3, 1]], dtype=int64))

In [ ]:
np.argmin(r,axis=1),np.argmax(r,axis=0)

(array([2, 1, 2], dtype=int64), array([1, 2, 1, 0, 1], dtype=int64))

In [ ]:
np.random.seed(42)
ts = pd.Series(np.random.randn(10),index=pd.date_range('1/1/2022',periods=10))
ts

2022-01-01    0.496714
2022-01-02   -0.138264
2022-01-03    0.647689
2022-01-04    1.523030
2022-01-05   -0.234153
2022-01-06   -0.234137
2022-01-07    1.579213
2022-01-08    0.767435
2022-01-09   -0.469474
2022-01-10    0.542560
Freq: D, dtype: float64

In [ ]:
a = np.random.rand(2,3) # scaled value bt 0-1 and of shape 2,3
b= np.random.random(2) # bt 0-1 but in 1D, no shape
c = np.random.randn(2,3) # sclaed bt -1---+1 and of given shape
d = np.linspace(-4,4,10)
e = np.random.randint(1,10,5)
a,b,c,d,e

(array([[0.18182497, 0.18340451, 0.30424224],
        [0.52475643, 0.43194502, 0.29122914]]),
 array([0.61185289, 0.13949386]),
 array([[-0.90802408, -1.4123037 ,  1.46564877],
        [-0.2257763 ,  0.0675282 , -1.42474819]]),
 array([-4.        , -3.11111111, -2.22222222, -1.33333333, -0.44444444,
         0.44444444,  1.33333333,  2.22222222,  3.11111111,  4.        ]),
 array([9, 3, 5, 3, 7]))